# syntax=docker/dockerfile:1
FROM golang:1.21-alpine as builder

WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN go build -v -o /bin/app

FROM alpine:3.18

COPY --from=builder /bin/app /bin/app

ENTRYPOINT [ "/bin/app" ]
