# syntax=docker/dockerfile:1
FROM golang:1.21-alpine as builder

WORKDIR /src
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod/ \
  go mod download -x
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod/ \
  go build -v -o /bin/app

FROM alpine:3.18

COPY --from=builder /bin/app /bin/app

ENTRYPOINT [ "/bin/app" ]
